### PR TITLE
Redirect v3 docs to v4 versions

### PR DESCRIPTION
**Pull request by jdamiba**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Looks good! Can you please remove the `python/v3` stuff from the Percy snapshot list?

**Comment by jdamiba** [comment]
@nicolaskruchten I pushed a commit here that removes the python/v3 stuff from the Percy snapshot list.

**Comment by nicolaskruchten** [comment]
Ok. Are you planning on expanding this PR to other sections?

**Comment by jdamiba** [comment]
No, I was planning on opening separate PRs for the remaining v3 docs. This one was to make sure I am doing it correctly.

**Comment by jdamiba** [comment]
@nicolaskruchten I've changed my mind- I will in fact continue adding commits to this PR until I have redirected all the v3 documentation posts with v4 equivalents.

**Comment by jdamiba** [comment]
@nicolaskruchten I think I got all the remaining v3 docs with my commits this morning. This PR is ready for review.

**Pull request merged**
