### PR TITLE
Add dash-vtk webinar banner

### PR DESCRIPTION
**Pull request by xhluca**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Check the percy diffs: the new banner overlaps the content.

**Comment by xhlulu** [comment]
You are right! What's the best way to adjust it? It seems hard to just change the same html files but I'm not sure how the website works exactly either.

**Comment by nicolaskruchten** [comment]
We've never yet figured out a reliable way to have two levels of banner like this unfortunately, so your options would be to either solve this problem once and for all by reworking a bunch of CSS, or to temporarily replace the Black Lives Matter banner.

**Comment by xhlulu** [comment]
@nicolaskruchten how much effort would it be to rework the CSS? Even with one banner the problem seems to be present.

**Comment by nicolaskruchten** [comment]
I have no strong feeling about how long it would take, but it feels to me like a few days for someone who knows CSS/HTML/browsers/mobile. To be honest, if I thought it was less than that I would have done this myself a long time ago :)

> Even with one banner the problem seems to be present, but not as apparent.

Yeah one of the Percy outputs looks odd but I've not been able to replicate this on a real browser

**Comment by jackparmer** [comment]
This could be a nice starter project for an incoming marketing hire, who will have some level of front-end programming & CSS experience. We can just leave this open for now until this new hire comes onboard in the next few months.

**Pull request closed without merging**
