### PR TITLE
move breadcrumb into header

### PR DESCRIPTION
**Pull request by jdamiba**
This PR moves the breadcrumb into the header.

Screenshot:
Screen Shot 2020-03-26 at 10 34 09 PM
Screen Shot 2020-03-26 at 10 32 47 PM

to do:

- [ ] fix position

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
This is the right idea, yep! While the breadcrumb trail is visible, though, the top bar should remain sticky as you scroll down the page.

**Comment by jdamiba** [comment]
@nicolaskruchten This PR is ready for review.

**Comment by nicolaskruchten** [comment]
Looks great! A few requests:

1. Remove the "back to LANG" from the sidebar in content pages (no longer necessary!)
2. Remove the `margin-top` from `#modal-input` to move the search box back up closer to the top nav
3. Add 20px of left margin to the breadcrumbs so they move away from the logo a bit
4. Set a breakpoint such that the font of the COVID banner shrinks before it wraps to two lines :)

**Comment by jdamiba** [comment]
@nicolaskruchten This PR has been updated with the changes you requested. 

Screenshot:

Screen Shot 2020-03-31 at 10 49 43 AM

**Comment by nicolaskruchten** [comment]
This is looking OK except for the landing page on mobile:

image

**Comment by nicolaskruchten** [comment]
Also right after the COVID-shrinking breakpoint, I now see a white gap here:

image

**Comment by jdamiba** [comment]
@nicolaskruchten I have updated the PR to address the issues you brought up. 

Screenshots

Screen Shot 2020-03-31 at 5 59 18 PM
Screen Shot 2020-03-31 at 5 58 26 PM

**Comment by nicolaskruchten** [comment]
Let's rebase this onto the no-COVID master and see what it looks like.

**Comment by jdamiba** [comment]
@nicolaskruchten PR has been updated with latest master revisions. 

Screen Shot 2020-04-01 at 9 09 57 AM

**Comment by nicolaskruchten** [comment]
Almost there! There's a new gap on the main page:

image

**Pull request merged**
