### PR TITLE
Update sidebar ad to Dash Club

### PR DESCRIPTION
**Pull request by red-patience**
Updates the sidebar ad to Dash Club as per @jingningzhang1's request.

This is not tested so @HammadTheOne please check that it behaves correctly. Thanks!

### CODE REVIEW

**Comment by HammadTheOne** [comment]
Looks fine to me, but I do want to note that I had to disable my ad-blocker to view it probably because it has "ad" in the URL. We might want to change that.

**Comment by red-patience** [comment]
That ad blocker is too clever! Okay lemme change that real quick 😅

**Comment by red-patience** [comment]
Okay fixed. Do you get the same thing on https://dash.plotly.com/ @HammadTheOne?

**Comment by HammadTheOne** [comment]
> Okay fixed. Do you get the same thing on https://dash.plotly.com/ @HammadTheOne?

Great, working fine now! And no, the one for the webinar on the Dash docs loads for me even with the adblock on.

**Review by HammadTheOne — APPROVED** [review]

**Comment by jingningzhang1** [comment]
Much appreciated @red-patience @HammadTheOne -- thank you!

**Pull request merged**
