### PR TITLE
restyle 404

### PR DESCRIPTION
**Pull request by jdamiba**
closes https://github.com/plotly/documentation/issues/1678
Screen Shot 2020-03-31 at 8 33 34 PM

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Style looks good. Now time to make the content more helpful! Let's get a search box in there somehow if there is `/python/` or `/javascript/` or `/r/` in the URL so they can search our docs directly? Maybe use Javascript to preload the search box with the URL subfragment with hyphens replaced by spaces, along with a "search" button they can click on that will bring up the modal? So like for the URL https://plotly.com/python/datashaader/ (note the extra `a`) we know they're in Python-land, and maybe searching for `datashaader` will come up with something? and yes, our search will get them to where they're going!

image

**Comment by jdamiba** [comment]
- [ ] get search modal to display on 404 page (change layout to base?)
- [ ] prepopulate search modal with URL
- [ ] if URL contains `/python`, `/javascript`, or `/r`, then provide a link to language index page

**Comment by jdamiba** [comment]
@nicolaskruchten I'd like to suggest that we merge this style update on its own. 

Adding the search modal to this page is more complicated than I had anticipated and I don't want that work to block this update, which looks more on brand than what we currently have in production.

**Comment by nicolaskruchten** [comment]
OK, in that case please:

* put a bit of whitespace above the header
* Change the text to "404 - Page not found!"
* Add a link below it: [Back to Graphing Libraries documentation home](https://plotly.com/graphing-libraries)

**Comment by jdamiba** [comment]
@nicolaskruchten I have updated this PR. 

Screenshot:

Screen Shot 2020-04-16 at 7 11 09 PM

**Comment by nicolaskruchten** [comment]
Can we make the link look more like a link? change color, make it underlined?

**Comment by jdamiba** [comment]
Screen Shot 2020-04-17 at 3 22 31 PM

**Pull request merged**
