### PR TITLE
replace homepage hero image

### PR DESCRIPTION
**Pull request by jdamiba**
Screen Shot 2020-03-25 at 7 51 32 PM

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Could you please:

1. make the whole hero thing shorter, such that the three language cards fit in the same screenful without scrolling?
2. add a bit of whitespace between the main and sub-titles there inside the hero

**Comment by jdamiba** [comment]
I have updated this PR.

Screen Shot 2020-03-26 at 1 09 42 PM

**Comment by nicolaskruchten** [comment]
Still a little shorter please! it's not all fitting on my laptop screen ;)

image

**Comment by nicolaskruchten** [comment]
actually i'll fiure out the right height, hang on

**Comment by nicolaskruchten** [comment]
pushed... can you take a look, LMK what you think?

**Pull request merged**
