### PR TITLE
order fixups

### PR DESCRIPTION
**Pull request by jdamiba**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
If you check in Percy, the Python index page Chart Studio section looks off... If you could manually set the order for those such that the first 4 have order 1/2/3/4 and have example_index set, it would be a nice improvement immediately, and would reduce the percy diffs in the next iteration when we get rid of example_index :)

**Comment by nicolaskruchten** [comment]
In fact I think we have the same problem in plotly.com/r in the chart studio section in prod today.

**Comment by jdamiba** [comment]
@nicolaskruchten I updated the order for Python and R Chart Studio Integrations sections. Please take another look at Percy.

**Comment by nicolaskruchten** [comment]
OK, much better, thanks!

**Pull request merged**
